# Enforces repository rules
repository:
  name: nexus-core
  description: "Core engine for modular space simulation"
  homepage: "https://nexuscosmos.tech"

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        contexts:
          - "build"
          - "lint"
      enforce_admins: false
