version: 2
updates:
  - package-ecosystem: "pip"  # For Python
    directory: "/"            # Root directory
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"  # Corrected name
    directory: "/.github/workflows"      # Corrected path
    schedule:
      interval: "monthly"
