name: "🐛 Bug Report"
description: "Report unexpected behavior"
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: checkboxes
    attributes:
      label: "Before reporting"
      options:
        - label: I've searched existing issues
          required: true
        - label: I've checked Discussions
        - label: This isn't a duplicate
          required: true

  - type: textarea
    attributes:
      label: "Expected Behavior"
      placeholder: "Scientific expectation"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Actual Behavior"
      placeholder: "What's happening instead?"

  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      placeholder: |
        1. Load module: `Sol:Earth`
        2. Run command: `simulate(100_years)`
        3. Observe position

  - type: dropdown
    attributes:
      label: "Affected System"
      options:
        - Physics engine
        - AI prediction
        - 3D rendering
      required: true

  - type: input
    attributes:
      label: "Version"
      placeholder: "nexus-core@0.3.1"
