blank_issues_enabled: false  # Force template usage
contact_links:
  - name: 🚀 Feature Request
    url: https://github.com/NexusCosmos/your-repo/issues/new?template=feature.yml
    about: Suggest a new module or enhancement
  - name: 🐛 Bug Report
    url: https://github.com/NexusCosmos/your-repo/issues/new?template=bug.yml
    about: Report unexpected behavior
  - name: ❓ Ask a Question
    url: https://github.com/NexusCosmos/your-repo/discussions
    about: Get help in Discussions
